services:
  - type: web
    name: argentBank-backend
    env: node
    plan: free
    branch: master
    buildCommand: npm install
    startCommand: npm start
    envVars:
      # - key: PORT
      #   value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  
# build:
#   npmInstall:
#     cacheVersion: v1