services:
  - type: web
    name: bank-argent-backend
    envVars:
      - key: NODE
        value: node
      # - key: PORT
      #   value: 3001
      - key: NODE_ENV
        value: production
    plan: free
    
build:
  npmInstall:
    cacheVersion: v1